apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: default
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    app: prometheus-node-exporter
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  type: ClusterIP
