apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-repo
          emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git
          command: [ 'sh', '-c', 'git clone https://github.com/chrodrigues/nginx-html.git /mnt/repo' ]
          volumeMounts:
            - name: nginx-repo
              mountPath: /mnt/repo
      containers:
        - image: nginx
          name: nginx
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          volumeMounts:
            - name: nginx-repo
              mountPath: /usr/share/nginx/html
