apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: prometheus-node-exporter