apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: default
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
    spec:
      containers:
        - name: prometheus-node-exporter
          image: prom/node-exporter:latest
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 50Mi
              cpu: 50m
          securityContext:
            privileged: true
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
