apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: homelab
  namespace: default
spec:
  general:
    serviceName: homelab
    version: 2.3.0
  dashboards:
    enable: true
    version: 2.3.0
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "50Gi"
      persistence:
        pvc:
          storageClass: openebs
          accessModes:
            - ReadWriteOnce
      nodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"