apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek
  labels:
    app: deepseek
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deepseek
  template:
    metadata:
      labels:
        app: deepseek
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: Exists
      containers:
        - name: ollama
          image: ollama/ollama:0.5.8-rc1rocm
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              nvidia.com/gpu: "1"
          ports:
          - name: http
            containerPort: 11434
            protocol: TCP


