apiVersion: v1
kind: Service
metadata:
  name: deepseek
  namespace: deepseek
spec:
  type: ClusterIP
  selector:
    app: deepseek
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP