apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIAR72PHH4AALI7J3M4"
  AWS_SECRET_ACCESS_KEY: "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"
