#cloud-config
disk_setup:
   ephmeral0:
       table_type: 'mbr'
       layout: 'auto'
   /dev/vdb:
       table_type: 'mbr'
       layout: true
       overwrite: false
fs_setup:
   - label: ephemeral0
     filesystem: 'ext4'
     device: '/dev/vdb1'
mounts:
 - [ vdb, /var/openebs/local, "ext4", "defaults,nofail", "0", "0" ]
users:
  - default
  - name: ${var.proxmox_vm_user}
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${trimspace(data.local_file.ssh_public_key.content)}
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    -  echo "PROXMOX_USERNAME=${var.proxmox_user_name}" > /tmp/credential.env
    -  echo "PROXMOX_PASSWORD=${var.proxmox_user_password}" >> /tmp/credential.env
    -  echo "PROXMOX_HOST=${var.proxmox_endpoint}" >> /tmp/credential.env
    - apt update
    - apt install -y qemu-guest-agent net-tools jq
    - timedatectl set-timezone America/Toronto
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - wget https://raw.githubusercontent.com/chrodrigues/biruleibe/main/terraform/proxmox/kubeadm_init.sh https://raw.githubusercontent.com/chrodrigues/biruleibe/main/terraform/proxmox/set_hostname.sh
    - chmod +x /kubeadm_init.sh /set_hostname.sh
    - /bin/bash /kubeadm_init.sh
    - /bin/bash /set_hostname.sh
    - echo "done" > /tmp/cloud-config.done