all:
  hosts:
    k8s-master-01:
      ansible_host: 192.168.100.50
      ansible_port: 22
    k8s-worker-0:
      ansible_host: 192.168.100.60
      ansible_port: 22
    k8s-worker-1:
      ansible_host: 192.168.100.61
      ansible_port: 22
    k8s-worker-2:
      ansible_host: 192.168.100.62
      ansible_port: 22
  children:
    k8s:
      hosts:
        k8s-master-01:
        k8s-worker-0:
        k8s-worker-1:
        k8s-worker-2:

